# Generated by Django 5.0.4 on 2024-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_row_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='id',
        ),
        migrations.AddField(
            model_name='row',
            name='index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
