# Generated by Django 5.0.4 on 2024-04-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_row_index_row_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='column10',
        ),
        migrations.RemoveField(
            model_name='row',
            name='column6',
        ),
        migrations.RemoveField(
            model_name='row',
            name='column7',
        ),
        migrations.RemoveField(
            model_name='row',
            name='column8',
        ),
        migrations.RemoveField(
            model_name='row',
            name='column9',
        ),
    ]
